INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (3, 'Nascimento', '2009-04-16 10:58:02.335000', 'Hoje, pela manhã, segundo as agências noticiosas mundiais, o Sol nasceu a Oriente.
Os governos de todo o mundo já enviaram os parabéns', false, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (2, 'Nova aplicação no firmamento português', '2009-04-16 10:49:58.497000', 'Certitools, uma nova aplicação produzida por uma pequena empresa da rua de Moçambique, passa a ser pré-instalada no computador Magalhães que o PM se prepara para distribuir na proxima visita à Antartida', false, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (1, 'A Lua acusada de conservadorismo', '2009-04-16 10:26:28.498000', 'Rama Calhau, em discurso, acusa a Lua de não inovar a órbita, contribuindo para manter a crise.
Os astrónomos reagiram através de comunicado', false, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (10, 'Módulo PEI já integra Medidas de Autoprotecção - artigo 21º do DL 220/2008', '2009-05-12 12:05:32.642000', 'O módulo Plano de Emergência do CertiTools já integra todas as Medidas de Autoprotecção referidas no artigo 21º do DL 220/2008, no sentido destas serem facilmente auditáveis, destacando-se a possibilidade de incluir, entre outros, os seguintes registos de segurança (medidas de autoprotecção do artigo 201º da Portaria 1532/2008 de 29 de Dezembro):

• Relatórios de vistoria
• Registo de anomalias
• Registos de acções de manutenção
• Registos modificações / alterações da instalação
• Registos de realização de trabalhos perigosos
• Registos de ocorrências de segurança contra incêndios
• Relatórios de intervenção de entidades externas
• Relatórios / registos de acções de formação
• Registos de simulacros', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (13, 'The Emergency Plan Module already incorporates the self-protection measures- Article 21º DL 220/2008', '2009-05-19 17:19:06.251000', 'For more information please contact us: 

  e-mail: certitools@certitecna.pt 
  Telf.: +351 218 148 011', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (17, 'Certitools ultrapassa os 4000 utilizadores', '2010-02-24 17:10:50.386000', '<p>J&aacute; s&atilde;o mais de 4000 os utilizadores que t&ecirc;m acesso e navegam no Certitools, acedem aos seus Planos de Emerg&ecirc;ncia e Planos de Preven&ccedil;&atilde;o.&nbsp;Uma faceta da&nbsp;seguran&ccedil;a&nbsp; agora muito mais acess&iacute;vel&nbsp;na vida di&aacute;ria destas entidades.&nbsp;</p>
<p>Acessibilidade e Simplicidade&nbsp;&nbsp;- dois objectivos Certitools agora partilhados por muitos.</p>', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (14, 'Safety Plan - A CertiTools Module', '2009-05-19 17:27:06.728000', 'For more information please contact us: 

  e-mail: certitools@certitecna.pt 
  Telf.: +351 218 148 011', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (11, 'Plano de Prevenção - Um módulo do Certitools', '2009-05-12 12:09:21.352000', '<p>PLANO DE PREVEN&Ccedil;&Atilde;O: um dos m&oacute;dulos do CertiTools em desenvolvimento que vem dar resposta &agrave; necessidade de garantir uma integra&ccedil;&atilde;o total de todos os documentos que constituem o Plano de Seguran&ccedil;a Interno (Plano de Emerg&ecirc;ncia Interno, Plano de Preven&ccedil;&atilde;o e Medidas de Autoprotec&ccedil;&atilde;o) conforme referido no Artigo 21&ordm; do novo Regime jur&iacute;dico da Seguran&ccedil;a Contra Inc&ecirc;ndios.</p>', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (15, 'Nova Release do Certitools', '2010-02-23 17:17:26.392000', '<p>Foi instalada uma nova release do Certitools. Entre outras funcionalidades, foi dado destaque &agrave; vertente internacional do Certitools,&nbsp;facilitando assim a&nbsp;navega&ccedil;&atilde;o na aplica&ccedil;&atilde;o por utilizadores que dominam outras linguas que n&atilde;o a portuguesa.&nbsp;&nbsp;</p>', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (18, 'Over 4000 Certitools Users', '2010-02-24 17:24:09.621000', '<p><span id="result_box" class="long_text"><span title="J&aacute; s&atilde;o mais de 4000 os utilizadores que t&ecirc;m acesso e navegam no Certitools, acedem aos seus Planos de Emerg&ecirc;ncia e Planos de Preven&ccedil;&atilde;o." onmouseout="this.style.backgroundColor=''#fff''" onmouseover="this.style.backgroundColor=''#ebeff9''" style="background-color: #fff">There&nbsp;are&nbsp;more than&nbsp;4000 users who&nbsp;now access and navigate in Certitools, access their Emergency Plans and Prevention Plans.&nbsp;</span><span title="Uma faceta da seguran&ccedil;a agora muito mais acess&iacute;vel na vida di&aacute;ria destas entidades." onmouseout="this.style.backgroundColor=''#fff''" onmouseover="this.style.backgroundColor=''#ebeff9''" style="background-color: #fff">A&nbsp;safety area now much more accessible in these entities daily life.<br />
<br />
</span><span title="Acessibilidade e Simplicidade - dois objectivos Certitools agora partilhados por muitos." onmouseout="this.style.backgroundColor=''#fff''" onmouseover="this.style.backgroundColor=''#ebeff9''" style="background-color: #fff">Accessibility and Simplicity - Two&nbsp;Certitools goals&nbsp;now shared by many. <br />
</span></span></p>', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (16, 'Lauched a new Release in Certitools', '2010-02-23 18:05:50.779000', '<p>A new release has been launched. Among other functionalities, we highlight the international area, where making it&nbsp;easier to navigate and explore the application&nbsp;by all those users that master other languages but not&nbsp;Portuguese has been an important target.</p>', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (19, 'Nova release  do Certitools', '2010-04-08 00:00:00.000000', '<p>Foi instalada uma nova release do Certitools. Porque o feedback dos nossos&nbsp;clientes &eacute; muito importante para n&oacute;s, as novas funcionalidades introduzidas s&atilde;o produto desse feedback em conjunto com uma an&aacute;lise de melhoria cont&iacute;nua a que regularmente nos propomos.</p>', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (20, 'New release lauched in Certitools', '2010-04-08 00:00:00.000000', '<p>A new release has been lauched. Our clients''&nbsp;feedback is of extreme importance to us. The new functionalities are the result of that feedback in conjunction with our analysis for continuous&nbsp;improvement<span id="result_box" class="medium_text"><span title="s&atilde;o produto desse feedback em conjunto com uma an&aacute;lise de melhoria cont&iacute;nua a que regularmente nos propomos." onmouseout="this.style.backgroundColor=''#fff''" onmouseover="this.style.backgroundColor=''#ebeff9''" style="background-color: #fff"><font size="3">.</font></span></span></p>', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (21, 'Nova release do Certitools já disponível', '2010-08-18 00:00:00.000000', '<p>Criar templates personalizados para os conte&uacute;dos do Plano de Emerg&ecirc;ncia e Plano de Preven&ccedil;&atilde;o foi uma das novas funcionalidades instaladas.</p>', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (22, 'New release available in Certitools', '2010-08-18 00:00:00.000000', '<p><span title="" te="Create custom templates for the contents of the Emergency Plan and Prevention Plan was one of the new features installed." se="Criar templates personalizados para os conte&uacute;dos do Plano de Emerg&ecirc;ncia e Plano de Preven&ccedil;&atilde;o foi uma das novas funcionalidades instaladas." closure_uid_rmwxwz="46" style="background-color: #fff">Creating customized templates for the contents of the Emergency Plan and Prevention Plan was one of the new features installed.</span></p>', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (26, 'Coimbra''s City Council PEE is in Certitools', '2011-08-01 00:00:00.000000', '<p><span class="hps" closure_uid_66tojo="279" pc="null">Coimbra City Council</span> <span class="hps" closure_uid_66tojo="280" pc="null">already has its</span> <span class="hps" closure_uid_66tojo="281" pc="null">Special&nbsp;E</span><span closure_uid_66tojo="282" pc="null">mergency</span> Plan for&nbsp;the <span class="hps" closure_uid_66tojo="286" pc="null">Old</span> Urban <span class="hps" closure_uid_66tojo="287" pc="null">Coimbra Center</span><span closure_uid_66tojo="291" pc="null"> available in </span><span class="hps" closure_uid_66tojo="292" pc="null">CertiTools</span><span closure_uid_66tojo="293" pc="null">.</span> <span class="hps" closure_uid_66tojo="294" pc="null">The advantages</span> <span class="hps" closure_uid_66tojo="295" pc="null">are clear and</span> are <span class="hps" closure_uid_66tojo="296" pc="null">related to</span> <span class="hps" closure_uid_66tojo="297" pc="null">the possibility of:</span><br closure_uid_66tojo="321" pc="null" />
<br closure_uid_66tojo="322" pc="null" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="hps" closure_uid_66tojo="298" pc="null">- Support the</span> <span class="hps" closure_uid_66tojo="299" pc="null">operationalization of</span> <span class="hps" closure_uid_66tojo="300" pc="null">Civil Protection</span> <span class="hps" closure_uid_66tojo="301" pc="null">Plans</span><span closure_uid_66tojo="302" pc="null">;</span><br closure_uid_66tojo="325" pc="null" />
<br closure_uid_66tojo="328" pc="null" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="hps" closure_uid_66tojo="303" pc="null">-</span> <span class="hps" closure_uid_66tojo="304" pc="null">Ensure consultation</span> <span class="hps" closure_uid_66tojo="305" pc="null">of the</span> <span class="hps" closure_uid_66tojo="306" pc="null">Special Emergency</span> <span class="hps" closure_uid_66tojo="307" pc="null">Plan</span>&nbsp;by <span class="hps" closure_uid_66tojo="309" pc="null">all</span> <span class="hps" closure_uid_66tojo="310" pc="null">Civil Protection</span> <span class="hps" closure_uid_66tojo="311" pc="null">Agents</span><span closure_uid_66tojo="312" pc="null">;</span><br closure_uid_66tojo="329" pc="null" />
<br closure_uid_66tojo="332" pc="null" />
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <span class="hps" closure_uid_66tojo="313" pc="null">-</span> <span class="hps" closure_uid_66tojo="314" pc="null">Include</span> other&nbsp;<span class="hps" closure_uid_66tojo="316" pc="null">Civil Protection</span> Plans or other&nbsp;Internal <span class="hps" closure_uid_66tojo="318" pc="null">Emergency Plans.</span></p>', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (25, 'New release available in Certitools', '2012-09-18 00:00:00.000000', '<p><span id="result_box" lang="en" closure_uid_66tojo="131" a="undefined" c="4" pc="null"><span class="hps" closure_uid_66tojo="248" pc="null">A&nbsp;new</span> <span class="hps" closure_uid_66tojo="249" pc="null">release</span> <span class="hps" closure_uid_66tojo="250" pc="null">is now available</span> in <span class="hps" closure_uid_66tojo="251" pc="null">CertiTools</span> <span class="hps" closure_uid_66tojo="252" pc="null">adding</span> <span class="hps" closure_uid_66tojo="253" pc="null">new features. A</span> special focus&nbsp;was implemented regarding&nbsp;<span class="hps" closure_uid_66tojo="255" pc="null">updating and revision</span> <span class="hps" closure_uid_66tojo="256" pc="null">of the</span> <span class="hps" closure_uid_66tojo="257" pc="null">Internal</span> <span class="hps" closure_uid_66tojo="258" pc="null">Safety Plans</span><span closure_uid_66tojo="259" pc="null">.</span></span></p>', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (28, 'Awareness Campaign at Forum Sintra', '2012-10-01 00:00:00.000000', '<p><span id="result_box" lang="en" c="4" a="undefined" closure_uid_o61osu="122" pc="null"><span class="hps" closure_uid_o61osu="191" pc="null">We just finished</span> <span class="hps" closure_uid_o61osu="192" pc="null">an awareness campaign</span> <span class="hps" closure_uid_o61osu="193" pc="null">of the</span> <span class="hps" closure_uid_o61osu="194" pc="null">Internal</span> <span class="hps" closure_uid_o61osu="195" pc="null">Safety Plan</span> of <span class="hps" closure_uid_o61osu="196" pc="null">Forum</span> <span class="hps" closure_uid_o61osu="197" pc="null">Sintra</span><span closure_uid_o61osu="198" pc="null">.</span> <span class="hps" closure_uid_o61osu="199" pc="null">During</span> <span class="hps" closure_uid_o61osu="200" pc="null">this initiative </span><span class="hps" closure_uid_o61osu="203" pc="null">CertiTools</span> was presented&nbsp;<span class="hps" closure_uid_o61osu="206" pc="null">individually to each</span>&nbsp;store <span class="hps" closure_uid_o61osu="208" pc="null">and</span>&nbsp;<span class="hps" closure_uid_o61osu="210" pc="null">​​a small</span> <span class="hps" closure_uid_o61osu="211" pc="null">awareness campaign was performed. A successful initiative that was appreciated by the people involved.</span><br closure_uid_o61osu="222" pc="null" />
<br closure_uid_o61osu="223" pc="null" />
<br closure_uid_o61osu="225" pc="null" />
<span class="hps" closure_uid_o61osu="213" pc="null">For more information on</span> <span class="hps" closure_uid_o61osu="214" pc="null">this and other</span> <span class="hps" closure_uid_o61osu="215" pc="null">activities</span> <span class="hps" closure_uid_o61osu="216" pc="null">contact us&nbsp;on</span> <span class="hps" closure_uid_o61osu="217" pc="null">the following email:</span> <span class="hps" closure_uid_o61osu="218" pc="null">certitools.PEI</span> <span class="hps" closure_uid_o61osu="219" pc="null">@</span> <span class="hps" closure_uid_o61osu="220" pc="null">certitecna.pt</span></span></p>
<div id="spell-place-holder" style="display: none; height: 25px">&nbsp;</div>
<p>&nbsp;</p>', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (24, 'Nova release do Certitools já disponível', '2012-09-18 00:00:00.000000', '<p>A nova release do CertiTools j&aacute; se encontra dispon&iacute;vel acrescentando novas funcionalidades nomeadamente no &acirc;mbito da actualiza&ccedil;&atilde;o e revis&atilde;o dos Planos de Seguran&ccedil;a Internos.</p>', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (23, 'PEE da Câmara Municipal de Coimbra no Certitools', '2011-08-01 00:00:00.000000', '<p>A C&acirc;mara Municipal de Coimbra j&aacute; tem o seu Plano Especial de Emerg&ecirc;ncia do Centro Urbano Antigo de Coimbra (CUA), dispon&iacute;vel no CertiTools. As vantagens s&atilde;o claras e prendem-se com&nbsp;a possibilidade&nbsp;de:</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;- Apoiar a operacionaliza&ccedil;&atilde;o dos Planos de Protec&ccedil;&atilde;o Civil;&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; - Garantir a consulta do Plano Especial de Emerg&ecirc;ncia por todos os Agentes de Protec&ccedil;&atilde;o Civil;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-&nbsp;Incluir outros Planos de Protec&ccedil;&atilde;o Civil ou Planos de Emerg&ecirc;ncia Internos.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>
<p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</p>', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (27, 'Campanha de sensibilização no Forum Sintra', '2012-10-01 00:00:00.000000', '<p>Termin&aacute;mos uma campanha de sensibiliza&ccedil;&atilde;o do Plano de Seguran&ccedil;a Interno do Forum&nbsp;Sintra. Durante a ac&ccedil;&atilde;o de sensabiliza&ccedil;&atilde;o foi apresentado o CertiTools individualmente a cada logista e efectuada uma pequena ac&ccedil;&atilde;o de sensibiliza&ccedil;&atilde;o. Uma iniciativa apreciada por todos envolvidos na ac&ccedil;&atilde;o.</p>
<p>Para mais informa&ccedil;&otilde;es sobre esta e outras ac&ccedil;&otilde;es contacte-nos&nbsp;para o email: <a href="mailto:certitools.PEI@certitecna.pt">certitools.PEI@certitecna.pt</a></p>', true, 1);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (30, 'New safety Management Module in August', '2015-07-20 00:00:00.000000', '<p><span id="result_box" lang="en"><span><span id="result_box" lang="en"><span>It is in</span> <span class="hps">final stages of development</span> <span class="hps">the Safety</span> <span class="hps">Management</span> <span class="hps">module, which</span> <span class="hps">supports the</span> <span class="hps">Internal</span> <span class="hps">Safety</span> <span class="hps">Plan</span> <span class="hps">modules</span><span>,</span> <span class="hps">Emergency</span> <span class="hps">Planning and</span> <span class="hps">Prevention Plan</span> <span class="hps">in its implementation</span> <span class="hps">phase.</span><br />
<span class="hps">The Safety</span> <span class="hps">Management</span> <span class="hps">Module</span><span>, among other features</span><span>,</span> <span class="hps">allows</span><span>:</span><br />
<span class="hps">&bull; Plan</span> <span class="hps">and manage</span> <span class="hps">activities</span> <span class="hps">within the</span> <span class="hps">security</span> <span class="hps">of each facility</span> <span class="hps">through a</span> <span class="hps atn">&quot;Safety</span> schedule<span>&quot;</span><span>;</span><br />
<span class="hps">&bull;</span> <span class="hps">Record all</span> <span class="hps">events</span> <span class="hps">related to the</span> <span class="hps">implementation of the</span> <span class="hps">Self-protection</span> <span class="hps">measures</span><span>;</span><br />
<span class="hps">&bull;</span> <span class="hps">Automatically send</span> <span class="hps">e-mail notices</span> <span class="hps">to</span> <span class="hps">previously identified</span> <span class="hps">recipients</span><span>;</span><br />
<span class="hps">&bull; To facilitate</span> <span class="hps">navigation and</span> <span class="hps">query</span> <span class="hps">of all data</span> <span class="hps">and</span> <span class="hps">information, in particular</span><span>,</span> <span class="hps">records</span><span>, reports,</span> <span class="hps">agenda,</span> <span class="hps">corrective action plans</span><span>, among others;</span><br />
<span class="hps">&bull; Access</span> <span class="hps">to information</span> <span class="hps">remotely</span>&nbsp;over<span class="hps"> a secure</span> <span class="hps atn">connection (</span><span>HTTPS)</span><span>, anytime</span> <span class="hps">and anywhere</span><span>.</span></span></span><br />
<br />
<span class="hps">For more information about</span> <span class="hps">this</span> <span class="hps">module</span> <span class="hps">please contact</span> <span class="hps">us at the</span> <span class="hps">email:</span> <span class="hps">certitools@certitecna.pt</span></span></p>', true, 2);
INSERT INTO public.news (id, title, creationdate, content, published, category_id) VALUES (29, 'Novo Módulo de Gestão de Segurança em Agosto', '2015-07-20 00:00:00.000000', '<p><span style="font-size: larger">Encontra-se em fase final de desenvolvimento o m&oacute;dulo Gest&atilde;o de Seguran&ccedil;a, o qual&nbsp; apoia os m&oacute;dulos Plano de Seguran&ccedil;a Interno, Plano de Emerg&ecirc;ncia e Plano de Preven&ccedil;&atilde;o na sua fase de implementa&ccedil;&atilde;o.<br />
O m&oacute;dulo Gest&atilde;o de Seguran&ccedil;a, entre outras funcionalidades, permite:<br />
&bull;&nbsp;Planear e gerir as atividades no &acirc;mbito da seguran&ccedil;a de cada estabelecimento, atrav&eacute;s de uma &ldquo;Agenda de Seguran&ccedil;a&rdquo;;<br />
&bull;&nbsp;Registar todos os eventos inerentes &agrave; implementa&ccedil;&atilde;o da Medidas de Autoprote&ccedil;&atilde;o online; <br />
&bull;&nbsp;Enviar automaticamente avisos por email para destinat&aacute;rios previamente identificados;<br />
&bull;&nbsp;Facilitar a navega&ccedil;&atilde;o e consulta de todos os dados e informa&ccedil;&otilde;es, nomeadamente, registos, relat&oacute;rios, agenda, planos de a&ccedil;&otilde;es corretivas, entre outros;<br />
&bull;&nbsp;Aceder remotamente &agrave; informa&ccedil;&atilde;o atrav&eacute;s de uma liga&ccedil;&atilde;o segura (HTTPS), a qualquer hora e em qualquer lugar.</span></p>
<p><span style="font-size: larger">Para mais </span><span style="font-size: larger">informa&ccedil;&otilde;es sobre este M&oacute;dulo contacte-nos&nbsp;para o email: certitools@certitecna.pt</span></p>', true, 1);