INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (1, 'pei completo para almada forum para testes. Remover depois dos testes', 'z csw -teste', 'pei_todo.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (2, null, 'ccb_Inst_Seg', 'ccb_1_20100824.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (49, 'TEMPLATE PEI', '04 PEI FORUM ALGARVE', 'PSI_Plano de Emergencia.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (9, null, 'CCB', 'PEI_CCB.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (12, null, 'CHP_Teste', 'Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (17, null, 'Estação Oriente_PSI', 'PSI_Estacao_Oriente.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (7, null, 'CHBA_LAGOS_PEI', 'PEI_LAGOS.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (18, null, 'ESTAÇÃO ORIENTE_REG_SEG', 'REG_SEG_ORIENTE.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (16, null, 'CHBA_PORTIMAO_PEI', 'PEI_PORTIMAO.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (15, null, 'ESTAÇÃO ORIENTE_PPREV', 'PPREV_ORIENTE.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (20, null, 'HOTEL DO CHIADO PEI', 'CHIADO_PEI_H.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (4, null, 'Galp_Torres_PSI', 'PSI_Torres.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (6, null, 'Galp_Alecrim_PSI', 'PSI.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (62, null, 'Almada_Forum_PSI', 'PSI_Almada_Forum.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (14, null, 'Estação Oriente_PSI_Anexos', 'PSI_Anexos_Estacao_Oriente.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (19, null, 'ARMAZENS CHIADO PSI', 'PSI_Armazem_Chiado.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (11, 'Template dos Procedimentos de Emergência da MTS - Metro Transportes do Sul', 'MTS_PE', 'MTS.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (63, null, 'Almada_Forum_PSI_Anexos', 'PSI_ANEXOS.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (27, 'Template de Registos de Segurança da MTS', 'MTS_RS', 'MTS_REG_SEC.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (46, null, 'FORUM SINTRA', 'SINTRA.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (13, 'Template do Plano de Prevenção da MTS', 'MTS_PPREV', 'MTS_P_PREV.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (133, null, 'SANEST_PSI_ETAR_GUIA_FASE_LIQ', 'PSI_ETAR_Guia_Fase_Liquida.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (83, null, 'ESCOLA NAUTICA_ANEXOS', 'PSI_Escola Náutica_ANEXOS_v2.doc', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (73, 'PSI', 'ESCOLA NAUTICA_PSI', 'PSI_ENautica.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (32, 'Procedimentos de Emergência', 'SGMOPTC_PE', 'PE_SGMOPTC.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (56, 'BPI CASAL RIBEIRO', 'PSI_Documento Base', '01_PSI.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (57, 'FORUM ALGARVE', 'PSI_Documento Base', 'PSI_Documento Base.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (37, null, 'TESTE_GERAL', 'pei_todo.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (36, 'Plano de Segurança Interno', 'MTS_PSI', 'PSI_MTS.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (40, null, 'TESTE TEXTO FORMATAVEL COM IMAGENS', 'TESTE.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (23, null, 'CHP_MJD_PEI', 'CHP_MJD_PEI_Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (60, null, 'MONTIJO_PP', 'teste - Cópia (2).docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (58, 'TESTE_DOC_BASE', 'TESTE_MONTIJO', 'PSI_Documento Base.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (72, null, 'Campus_Justica_Estrutura_Operacional', 'Estrutura_Operacional_Emergencia.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (75, null, 'montijo_teste2', 'teste_montijo_2.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (76, null, 'PP_MONTIJO', 'PP_MONTIJO.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (81, null, 'BPI_Casal Ribeiro_PSI', 'PSI_Casal_Ribeiro.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (50, null, '02 PPREV FORUM ALGARVE', 'PSI_Plano Prevencao.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (51, null, '03 REGISTO SEGURANCA FORUM ALGARVE', 'PSI_Registos de Seguranca.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (21, null, 'CHP_HSA_PEI', 'CHP_HSA_PEI_Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (33, 'Plano de Segurança Interno', 'SGMOPTC_PSI', 'PSI_SGMOPTC_20110630.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (34, 'Registos de Segurança', 'SGMOPTC_REG_SEG', 'REG_SEG_SGMOPTC_20110630.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (35, 'Plano de Prevenção', 'SGMOPTC_PPREV', 'PPREV_SGMOPTC_20110701.docx', 3);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (88, null, 'BPI_Comércio_PSI_Anexos', 'BPI_Comércio_PSI_Anexos.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (87, null, 'BPI_Comércio_PSI', 'PSI_Comercio.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (82, null, 'BPI_Casal Ribeiro_PSI_Anexos', 'PSI_Anexos_Casal_Ribeiro.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (93, null, 'BPI_Torre_E_PSI_Anexos', 'BPI_Torre_E_PSI_Anexos.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (94, null, 'BPI_Torre_H_PSI', 'PSI_Torre_H.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (86, null, 'BPI_Jean Monnet_PSI_Anexos', 'PSI_Anexos_Jean_Monnet.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (68, null, 'BPI_Almirante Barroso_PSI', 'PSI_Almirante_Barroso.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (92, null, 'BPI_Torre_E_PSI', 'PSI_Torre_E.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (99, null, 'BPI_Boavista II_PSI_Anexos', 'BPI_Boavista II_PSI_Anexos.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (91, null, 'BPI_Município_PSI_Anexos', 'PSI_Anexos_Município.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (77, null, 'BPI_Município_PSI', 'PSI_Município.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (96, null, 'BPI_Boavista I_PSI', 'PSI_Boavista I.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (97, null, 'BPI_Boavista I_PSI_ANEXOS', 'PSI_Anexos_Boavista I.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (61, null, 'TESTE_LINK', 'Documentação.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (47, 'TEMPLATE PSI FORUM ALGARVE', 'Forum Algarve_PSI', 'Forum Algarve_PSI_Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (98, null, 'BPI_Boavista II_PSI', 'PSI_Boavista II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (102, null, 'BPI_Tenente Valadim_PSI', 'PSI_Tenente_Valadim.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (100, null, 'BPI_Pedro Hispano_PSI', 'PSI_Pedro_Hispano.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (101, null, 'BPI_Pedro Hispano_PSI_Anexos', 'PSI_Anexos_Pedro_Hispano.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (95, null, 'BPI_Torre_H_PSI_Anexos', 'PSI_Anexos_Torre_H.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (103, null, 'BPI_Tenente Valadim_PSI_Anexos', 'PSI_Anexos_Tenente_Valadim.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (104, null, 'BPI_Sá da Bandeira 20_PSI', 'PSI_Sá_Bandeira_20.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (105, null, 'BPI_Sá da Bandeira 20_PSI_Anexos', 'PSI_Anexos_Sa_Bandeira_20.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (106, null, 'BPI_Sá da Bandeira 78_PSI', 'PSI_Sa_Bandeira_78.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (110, null, 'BPI_Galiza_PSI', 'PSI_Galiza.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (111, null, 'BPI_Galiza_PSI_Anexos', 'PSI_Anexos_Galiza.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (114, null, 'BPI_Arquivo da Maia_PSI', 'PSI_Arquivo_da_Maia.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (113, null, 'BPI_Armazém D. João IV_PSI_Anexos', 'PSI_Anexos_Armazem_D_Joao_IV.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (112, null, 'BPI_Armazém D. João IV_PSI', 'PSI_Armazem_D_Joao_IV.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (22, null, 'CHP_MPIA_PEI', 'CHP_MPIA_PEI_Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (109, null, 'BPI_Sampaio Bruno_PSI_Anexos', 'PSI_Anexos_Sampaio_Bruno.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (108, null, 'BPI_Sampaio Bruno_PSI', 'PSI_Sampaio_Bruno.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (132, null, 'Millennium bcp_PSI_Anexos_Palacio_Atlantico', 'PSI_Anexos_Palacio_Atlantico_Millennium_bcp.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (122, null, 'Forum Algarve_PSI_Anexos', 'Forum Algarve_PSI_Anexos_Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (154, null, 'Banco de Portugal_Edif_Sede', 'PSI_BdP_EDIF_SEDE.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (64, null, 'BPI_Jean Monnet_PSI', 'PSI_Jean_Monnet.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (123, 'PSI BASE', 'SN_MAIA_PSI', 'PSI_SN_MAIA.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (140, null, 'Banco de Portugal - PSI ANEXOS', 'PSI_Anexos_BdP_EDIF_SEDE.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (155, null, 'Banco de Portugal_Edif_Sede_Anexos', 'PSI_Anexos_BdP_EDIF_SEDE.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (134, null, 'SANEST_PSI_ANEXOS_ETAR_GUIA_FASE_LIQ', 'PSI_Anexos_ETAR_Guia_Fase_Liquida.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (124, 'PSI ANEXOS', 'SN_MAIA_PSI_ANEXOS', 'PSI_Anexos_SN_MAIA.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (107, null, 'BPI_Sá da Bandeira 78_PSI_Anexos', 'PSI_Anexos_Sa _Bandeira_78.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (125, null, 'Forum_Madeira_PSI', 'PSI.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (126, null, 'Forum_Madeira_PSI_Anexos', 'PSI_ANEXOS.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (135, null, 'SANEST_PSI_ETAR_GUIA_FASE_SOL', 'PSI_ETAR_Guia_Fase_Solida.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (117, null, 'BPI_Braamcamp_PSI_Anexos', 'PSI_Anexos_Braamcamp.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (116, null, 'BPI_Braamcamp_PSI', 'PSI_Braamcamp.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (118, null, 'BPI_Tivoli_PSI', 'PSI_Tivoli.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (141, null, 'Galp_Torres_PSI_Anexos', 'PSI_Torres_ANEXOS.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (120, null, 'BPI_Armazém da Portela_PSI', 'PSI_Armazem_da_Portela.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (173, null, 'TAGUSPARK_QA_PSI_Anexos', 'PSI_Anexos_Qualidade  A.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (84, null, 'BPI_Almirante Barroso_PSI_Anexos', 'BPI_Almirante Barroso_PSI_Anexos.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (174, null, 'TAGUSPARK_QB_PSI', 'PSI_Qualidade B.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (137, null, 'SANEST_PSI_FLOR DA MURTA', 'PSI_Sanest_Flor da Murta.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (138, null, 'SANEST_PSI _ANEXOS_FLOR DA MURTA', 'PSI_Anexos_Sanest_Flor da Murta.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (127, null, 'CHP_MJD_PSI', 'CHP_MJD_PSI_Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (39, 'Plano de segurança interno da Uni. Hosp. Porto - Santo António', 'CHP_HSA_PSI', 'CHP_HSA_PSI_Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (128, null, 'CHP_MPIA_PSI', 'CHP_MPIA_PSI_Template.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (115, null, 'BPI_Arquivo da Maia_PSI_Anexos', 'PSI_Anexos_Arquivo_da_Maia.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (119, null, 'BPI_Tivoli_PSI_Anexos', 'PSI_Anexos_Tivoli.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (121, null, 'BPI_Armazém da Portela_PSI_Anexos', 'PSI_Anexos_Armazem_da_Portela.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (139, null, 'Banco de Portugal - PSI', 'PSI_Edificio Portugal.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (129, null, 'Millennium_bcp_PSI_Malhoa_27', 'PSI_Malhoa27_Millennium_bcp.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (130, null, 'Millennium_bcp_PSI_Anexos_Malhoa_27', 'PSI_Anexos_Malhoa27_Millennium_bcp.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (131, null, 'Millennium_bcp_PSI_Palacio_Atlantico', 'PSI_Palacio_Atlantico_Millennium_bcp.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (142, null, 'PSI_Atrium_Saldanha', 'PSI_Atrium_Saldanha.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (143, null, 'PSI_Atrium_Saldanha_Anexos', 'PSI_Anexos_Atrium_Saldanha.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (156, null, 'BdP_Edficio Rossio', 'PSI_BdP_Edificio Rossio.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (157, null, 'BdP_Edficio Rossio_Anexos', 'PSI_Anexos_BdP_Edificio Rossio.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (158, null, 'BdP_Edficio Crucifixo', 'PSI_BdP_Edificio Crucifixo.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (159, null, 'BdP_Edficio Crucifixo_Anexos', 'PSI_Anexos_BdP_Edificio Crucifixo.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (144, null, 'Galp_Alecrim_PSI_Anexos', 'PSI_ANEXOS.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (145, null, 'ARMAZENS CHIADO PSI_Anexos', 'PSI_Anexos_Armazem_Chiado.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (148, null, 'Forum Viseu_PSI_Anexos', 'PSI_Anexos_Forum Viseu.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (149, null, 'Forum Viseu_PSI', 'PSI_Forum Viseu.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (150, null, 'BdP_Quinta Fonte Santa_PSI', 'PSI_BdP_Quinta Fonte Santa.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (166, null, 'TNT_Head_Office_Lisboa_PSI', 'PSI_TNT_Head_Office_Lisboa.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (175, null, 'TAGUSPARK_QB_PSI_Anexos', 'PSI_Anexos_Qualidade  B.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (160, null, 'Hospital Distrital de Santarém', 'PSI_HDSantarem.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (161, null, 'Hospital Distrital de Santarém_Anexos', 'PSI_Anexos_HDSantarem.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (151, null, 'BdP_Quinta Fonte Santa_Anexos', 'PSI_Anexos_BdP_Quinta Fonte Santa.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (162, null, 'BdP_Edificio Olivais', 'PSI_BdP_EDIF_Olivais.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (238, null, 'PSI E.Nautica Anexos', 'PSI_E.Náutica_ANEXOS_FINAL.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (163, null, 'BdP_Edificio Olivais_Anexos', 'PSI_Anexos_BdP_EDIF_Olivais.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (165, null, 'TNT_DEPOT Coimbra PSI_Anexos', 'PSI_Anexos_TNT_Depot_Coimbra.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (146, null, 'TNT_DEPOT_Lisboa_PSI', 'PSI_TNT_Depot_Lisboa.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (147, null, 'TNT_DEPOT_Lisboa_PSI_Anexos', 'PSI_Anexos_TNT_Depot_Lisboa.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (164, null, 'TNT_DEPOT_Coimbra_PSI', 'PSI_TNT_Depot_Coimbra.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (176, null, 'TAGUSPARK_QC_PSI', 'PSI_Qualidade C.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (168, null, 'Inditex-Zara Vasco da Gama_PSI', 'PSI_Inditex_Zara_Vasco da Gama.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (169, null, 'Inditex-Zara Vasco da Gama_PSI_Anexos', 'PSI_Anexos_Inditex_Zara_Vasco da Gama.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (177, null, 'TAGUSPARK_QC_PSI_Anexos', 'PSI_Anexos_Qualidade  C.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (167, null, 'TNT_Head_Office_Lisboa_PSI_Anexos', 'PSI_Anexos_TNT_Head_Office_Lisboa.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (170, null, 'TAGUSPARK_NC_PSI', 'PSI_Nucleo Central.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (171, null, 'TAGUSPARK_NC_PSI_Anexos', 'PSI_Anexos_Nucleo Central.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (172, null, 'TAGUSPARK_QA_PSI', 'PSI_Qualidade A.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (178, null, 'TAGUSPARK_ED_CIENCAII_PSI', 'PSI_Ciencia II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (179, null, 'TAGUSPARK_ED_CIENCAII_PSI_ANEXOS', 'PSI_Anexos_Ciencia II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (180, null, 'TAGUSPARK_ED_INOV I_PSI', 'PSI_Inovação I.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (181, null, 'TAGUSPARK_ED_INOV I_PSI_ANEXOS', 'PSI_Anexos_Inovação I.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (182, null, 'TAGUSPARK_ED_INOV II_PSI', 'PSI_Inovação II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (183, null, 'TAGUSPARK_ED_INOV II_PSI_ANEXOS', 'PSI_Anexos_Inovação II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (184, null, 'TAGUSPARK_ED_INOV III_PSI', 'PSI_Inovação III.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (185, null, 'TAGUSPARK_ED_INOV III_PSI_ANEXOS', 'PSI_Anexos_Inovação III.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (186, null, 'TAGUSPARK_ED_INOV IV_PSI', 'PSI_Inovação IV.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (187, null, 'TAGUSPARK_ED_INOV IV_PSI_ANEXOS', 'PSI_Anexos_Inovação IV.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (188, null, 'Campus da Justiça_PSI', 'PSI_Campus Justiça.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (152, null, 'Autoeuropa PSI', 'PSI_AutoEuropa.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (237, null, 'PSI Escola Nautica', 'PSI_ENautica.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (189, null, 'Campus da Justiça_PSI_Anexos', 'PSI_Anexos_Campus Justiça.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (216, null, 'Banco BPI - Edif_Centrais_14_Tabacaria_PSI', 'PSI_Tabacaria.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (217, null, 'Banco BPI - Edif_Centrais_14_Tabacaria_PSI_Anexos', 'PSI_Anexos_Tabacaria.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (201, null, 'Banco BPI - Edif_Centrais_06_Torre H_PSI_Anexos', 'PSI_Anexos_Torre_H.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (202, null, 'Banco BPI - Edif_Centrais_07_Braamcamp_PSI', 'PSI_Braamcamp.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (203, null, 'Banco BPI - Edif_Centrais_07_Braamcamp_PSI_Anexos', 'PSI_Anexos_Braamcamp.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (136, null, 'SANEST_PSI _ANEXOS_ETAR_GUIA_FASE_SOL', 'PSI_Anexos_ETAR_Guia_Fase_Solida.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (204, null, 'Banco BPI - Edif_Centrais_08_Armazém_Portela_PSI', 'PSI_Armazém_Portela.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (218, null, 'Banco BPI - Edif_Centrais_15_Campião_PSI', 'PSI_Campião.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (205, null, 'Banco BPI - Edif_Centrais_08_Armazém_Portela_PSI_Anexos', 'PSI_Anexos_Armazém_Portela.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (206, null, 'Banco BPI - Edif_Centrais_09_Boavista I_PSI', 'PSI_Boavista_I.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (207, null, 'Banco BPI - Edif_Centrais_09_Boavista I_PSI_Anexos', 'PSI_Anexos_Boavista_I.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (208, null, 'Banco BPI - Edif_Centrais_10_Boavista II_PSI', 'PSI_Boavista_II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (209, null, 'Banco BPI - Edif_Centrais_10_Boavista II_PSI_Anexos', 'PSI_Anexos_Boavista_II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (219, null, 'Banco BPI - Edif_Centrais_15_Campião_PSI_Anexos', 'PSI_Anexos_Campião.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (210, null, 'Banco BPI - Edif_Centrais_11_Tenente_Valadim_PSI', 'PSI_Tenente_Valadim.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (211, null, 'Banco BPI - Edif_Centrais_11_Tenente_Valadim_PSI_Anexos', 'PSI_Anexos_Tenente_Valadim.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (221, null, 'Banco BPI - Edif_Centrais_16_Sampaio_Bruno_PSI', 'PSI_Sampaio_Bruno.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (220, null, 'Banco BPI - Edif_Centrais_16_Sampaio_Bruno_PSI_Anexos', 'PSI_Anexos_Sampaio_Bruno.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (222, null, 'Banco BPI - Edif_Centrais_17_Galiza_PSI', 'PSI_Galiza.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (223, null, 'Banco BPI - Edif_Centrais_17_Galiza_PSI_Anexos', 'PSI_Anexos_Galiza.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (224, null, 'Banco BPI - Edif_Centrais_18_Armazém_D._João_IV_PSI', 'PSI_Arm_D_Joao_IV.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (232, null, 'TAGUSPARK_ED_TEC III_PSI', 'PSI_Tecnologia III.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (225, null, 'Banco BPI - Edif_Centrais_18_Armazém_D._João_IV_PSI_Anexos', 'PSI_Anexos_Arm_D_Joao_IV.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (226, null, 'Banco BPI - Edif_Centrais_19_Arquivo_Maia_PSI', 'PSI_Arquivo Maia.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (227, null, 'Banco BPI - Edif_Centrais_19_Arquivo_Maia_PSI_Anexos', 'PSI_Anexos_Arquivo Maia.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (234, null, 'TAGUSPARK_ED_TEC IV_PSI', 'PSI_Tecnologia IV.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (236, 'TESTE', 'Escola Nautica_PSI_TESTE', 'PSI_ENautica.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (229, null, 'TAGUSPARK_ED_TEC I_PSI_ANEXOS', 'PSI_Anexos_Tecnologia I_f.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (233, null, 'TAGUSPARK_ED_TEC III_PSI_ANEXOS', 'PSI_Anexos_Tecnologia III.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (235, null, 'TAGUSPARK_ED_TEC IV_PSI_ANEXOS', 'PSI_Anexos_Tecnologia IV.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (190, null, 'Banco BPI - Edif_Centrais_01_Casal Ribeiro_PSI', 'PSI_Casal_Ribeiro.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (191, null, 'Banco BPI - Edif_Centrais_01_Casal Ribeiro_PSI_Anexos', 'PSI_Anexos_Casal_Ribeiro.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (192, null, 'Banco BPI - Edif_Centrais_02_Almirante Barroso_PSI', 'PSI_Almirante_Barroso.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (193, null, 'Banco BPI - Edif_Centrais_02_Almirante Barroso_PSI_Anexos', 'PSI_Anexos_Almirante_Barroso.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (194, null, 'Banco BPI - Edif_Centrais_03_Jean Monnet_PSI', 'PSI_Jean_Monnet.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (195, null, 'Banco BPI - Edif_Centrais_03_Jean Monnet_PSI_Anexos', 'PSI_Anexos_Jean_Monnet.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (196, null, 'Banco BPI - Edif_Centrais_04_Comércio_PSI', 'PSI_Comércio.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (153, null, 'Autoeuropa_PSI_Anexos', 'PSI_Anexos_AutoEuropa.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (230, null, 'TAGUSPARK_ED_TEC II_PSI', 'PSI_Tecnologia II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (231, null, 'TAGUSPARK_ED_TEC II_PSI_ANEXOS', 'PSI_Anexos_Tecnologia II.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (228, null, 'TAGUSPARK_ED_TEC I_PSI', 'PSI_Tecnologia I.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (212, null, 'Banco BPI - Edif_Centrais_12_Pedro_Hispano_PSI', 'PSI_Pedro_Hispano.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (197, null, 'Banco BPI - Edif_Centrais_04_Comércio_PSI_Anexos', 'PSI_Anexos_Comércio.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (199, null, 'Banco BPI - Edif_Centrais_05_Município_PSI', 'PSI_Município.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (198, null, 'Banco BPI - Edif_Centrais_05_Município_PSI_Anexos', 'PSI_Anexos_Município.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (200, null, 'Banco BPI - Edif_Centrais_06_Torre H_PSI', 'PSI_Torre_H.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (213, null, 'Banco BPI - Edif_Centrais_12_Pedro_Hispano_PSI_Anexos', 'PSI_Anexos_Pedro_Hispano.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (214, null, 'Banco BPI - Edif_Centrais_13_Sá_Bandeira_PSI', 'PSI_Sa_Bandeira.docx', 2);
INSERT INTO public.templatedocx (id, observations, title, filename, module_id) VALUES (215, null, 'Banco BPI - Edif_Centrais_13_Sá_Bandeira_PSI_Anexos', 'PSI_Anexos_Sa_Bandeira.docx', 2);