INSERT INTO public.legaldocumenttype (id, name) VALUES (228, 'Acórdão');
INSERT INTO public.legaldocumenttype (id, name) VALUES (229, 'Acórdão (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (230, 'Acordo');
INSERT INTO public.legaldocumenttype (id, name) VALUES (231, 'Alvará');
INSERT INTO public.legaldocumenttype (id, name) VALUES (232, 'Anúncio');
INSERT INTO public.legaldocumenttype (id, name) VALUES (233, 'Anúncio (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (234, 'Anúncio de concurso urgente');
INSERT INTO public.legaldocumenttype (id, name) VALUES (235, 'Anúncio de procedimento');
INSERT INTO public.legaldocumenttype (id, name) VALUES (236, 'Assento');
INSERT INTO public.legaldocumenttype (id, name) VALUES (237, 'Aviso');
INSERT INTO public.legaldocumenttype (id, name) VALUES (238, 'Aviso (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (239, 'Aviso de contumácia');
INSERT INTO public.legaldocumenttype (id, name) VALUES (240, 'Aviso de prorrogação de prazo');
INSERT INTO public.legaldocumenttype (id, name) VALUES (241, 'Aviso do Banco de Portugal');
INSERT INTO public.legaldocumenttype (id, name) VALUES (242, 'Balancete');
INSERT INTO public.legaldocumenttype (id, name) VALUES (243, 'Contrato');
INSERT INTO public.legaldocumenttype (id, name) VALUES (244, 'Contrato (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (245, 'Decisão');
INSERT INTO public.legaldocumenttype (id, name) VALUES (246, 'Decisão (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (247, 'Declaração');
INSERT INTO public.legaldocumenttype (id, name) VALUES (248, 'Declaração (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (249, 'Declaração de Rectificação');
INSERT INTO public.legaldocumenttype (id, name) VALUES (250, 'Decreto');
INSERT INTO public.legaldocumenttype (id, name) VALUES (251, 'Decreto do Governo');
INSERT INTO public.legaldocumenttype (id, name) VALUES (252, 'Decreto do Ministro da República');
INSERT INTO public.legaldocumenttype (id, name) VALUES (253, 'Decreto do Ministro da República para a Região Autónoma da Madeira');
INSERT INTO public.legaldocumenttype (id, name) VALUES (254, 'Decreto do Ministro da República para a Região Autónoma dos Açores');
INSERT INTO public.legaldocumenttype (id, name) VALUES (255, 'Decreto do Presidente da República');
INSERT INTO public.legaldocumenttype (id, name) VALUES (256, 'Decreto Legislativo Regional');
INSERT INTO public.legaldocumenttype (id, name) VALUES (257, 'Decreto Regional');
INSERT INTO public.legaldocumenttype (id, name) VALUES (258, 'Decreto Regulamentar');
INSERT INTO public.legaldocumenttype (id, name) VALUES (259, 'Decreto Regulamentar Regional');
INSERT INTO public.legaldocumenttype (id, name) VALUES (260, 'Decreto-Lei');
INSERT INTO public.legaldocumenttype (id, name) VALUES (261, 'Deliberação');
INSERT INTO public.legaldocumenttype (id, name) VALUES (262, 'Deliberação (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (263, 'Deliberação da Assembleia da República');
INSERT INTO public.legaldocumenttype (id, name) VALUES (264, 'Despacho');
INSERT INTO public.legaldocumenttype (id, name) VALUES (265, 'Despacho (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (266, 'Despacho conjunto');
INSERT INTO public.legaldocumenttype (id, name) VALUES (267, 'Despacho do Ministro da Economia');
INSERT INTO public.legaldocumenttype (id, name) VALUES (268, 'Despacho normativo');
INSERT INTO public.legaldocumenttype (id, name) VALUES (269, 'Despacho Regional');
INSERT INTO public.legaldocumenttype (id, name) VALUES (270, 'Despacho Regulamentar');
INSERT INTO public.legaldocumenttype (id, name) VALUES (271, 'Despacho Regulamentar Regional');
INSERT INTO public.legaldocumenttype (id, name) VALUES (272, 'Directiva');
INSERT INTO public.legaldocumenttype (id, name) VALUES (273, 'Directiva da AACS');
INSERT INTO public.legaldocumenttype (id, name) VALUES (274, 'Edital');
INSERT INTO public.legaldocumenttype (id, name) VALUES (275, 'Edital (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (276, 'Édito');
INSERT INTO public.legaldocumenttype (id, name) VALUES (277, 'Instrução');
INSERT INTO public.legaldocumenttype (id, name) VALUES (278, 'Instruções');
INSERT INTO public.legaldocumenttype (id, name) VALUES (279, 'Jurisprudência');
INSERT INTO public.legaldocumenttype (id, name) VALUES (280, 'Lei');
INSERT INTO public.legaldocumenttype (id, name) VALUES (281, 'Lei Constitucional');
INSERT INTO public.legaldocumenttype (id, name) VALUES (282, 'Lei Orgânica');
INSERT INTO public.legaldocumenttype (id, name) VALUES (283, 'Listagem');
INSERT INTO public.legaldocumenttype (id, name) VALUES (284, 'Listagem (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (285, 'Louvor');
INSERT INTO public.legaldocumenttype (id, name) VALUES (286, 'Louvor (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (287, 'Mapa');
INSERT INTO public.legaldocumenttype (id, name) VALUES (288, 'Mapa (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (289, 'Mapa Oficial');
INSERT INTO public.legaldocumenttype (id, name) VALUES (290, 'Moção');
INSERT INTO public.legaldocumenttype (id, name) VALUES (291, 'Moção de Confiança');
INSERT INTO public.legaldocumenttype (id, name) VALUES (292, 'Parecer');
INSERT INTO public.legaldocumenttype (id, name) VALUES (293, 'Parecer do Conselho de Estado');
INSERT INTO public.legaldocumenttype (id, name) VALUES (294, 'Portaria');
INSERT INTO public.legaldocumenttype (id, name) VALUES (295, 'Portaria (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (296, 'Preâmbulo Decreto Lei');
INSERT INTO public.legaldocumenttype (id, name) VALUES (297, 'Protocolo');
INSERT INTO public.legaldocumenttype (id, name) VALUES (298, 'Recomendação');
INSERT INTO public.legaldocumenttype (id, name) VALUES (299, 'Recomendação do Conselho');
INSERT INTO public.legaldocumenttype (id, name) VALUES (300, 'Rectificação');
INSERT INTO public.legaldocumenttype (id, name) VALUES (301, 'Rectificação (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (302, 'Rectificação de contumácia');
INSERT INTO public.legaldocumenttype (id, name) VALUES (303, 'Recurso');
INSERT INTO public.legaldocumenttype (id, name) VALUES (304, 'Regimento');
INSERT INTO public.legaldocumenttype (id, name) VALUES (305, 'Regimento da Assembleia da República');
INSERT INTO public.legaldocumenttype (id, name) VALUES (306, 'Regimento do Conselho de Estado');
INSERT INTO public.legaldocumenttype (id, name) VALUES (307, 'Regulamento');
INSERT INTO public.legaldocumenttype (id, name) VALUES (308, 'Regulamento CE');
INSERT INTO public.legaldocumenttype (id, name) VALUES (309, 'Regulamento da CMVM');
INSERT INTO public.legaldocumenttype (id, name) VALUES (310, 'Regulamento interno');
INSERT INTO public.legaldocumenttype (id, name) VALUES (311, 'Relatório');
INSERT INTO public.legaldocumenttype (id, name) VALUES (312, 'Resolução');
INSERT INTO public.legaldocumenttype (id, name) VALUES (313, 'Resolução (extracto)');
INSERT INTO public.legaldocumenttype (id, name) VALUES (314, 'Resolução da Assembleia da República');
INSERT INTO public.legaldocumenttype (id, name) VALUES (315, 'Resolução da Assembleia Legislativa Regional');
INSERT INTO public.legaldocumenttype (id, name) VALUES (316, 'Resolução da Assembleia Legislativa Regional dos Açores');
INSERT INTO public.legaldocumenttype (id, name) VALUES (317, 'Resolução da Assembleia Regional');
INSERT INTO public.legaldocumenttype (id, name) VALUES (318, 'Resolução do Conselho de Ministros');
INSERT INTO public.legaldocumenttype (id, name) VALUES (319, 'Resolução do Tribunal de Contas');