INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (162, 'Código Penal', 3, 2, 2, 19);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (71, 'Movimentação Mecânica Cargas', 3, 1, 1, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (218, 'Radioactivas', 3, 4, 4, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (138, 'Biocombustíveis', 3, 6, 6, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (82, 'Tabaco', 3, 2, 2, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (219, 'Protecção de materiais nucleares', 2, 2, 2, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (226, 'Escolas e Creches', 3, 2, 2, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (104, 'Radiações', 3, 27, 25, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (178, 'Estabelecimentos e Actividades', 2, 83, 75, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (220, 'Hospitalares', 3, 1, 1, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (149, 'Geral', 3, 15, 13, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (212, 'Segurança Rodoviária', 2, 75, 71, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (213, 'Geral', 3, 75, 71, 212);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (167, 'Geral', 3, 11, 9, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (206, 'Planos de Ordenamento', 3, 7, 6, 32);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (123, 'Pilhas e Acumuladores', 3, 4, 4, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (210, 'ZEC', 3, 1, 1, 207);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (211, 'SIC', 3, 1, 1, 207);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (164, 'Geral', 3, 27, 21, 31);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (25, 'Distrital', 2, 1, 0, 4);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (208, 'Geral', 3, 34, 30, 207);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (134, 'Poluentes Atmosféricos', 3, 19, 17, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (79, 'Agentes Biológicos', 3, 8, 8, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (207, 'Ordenamento do Território', 2, 258, 251, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (67, 'Instalações Eléctricas', 3, 24, 24, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (72, 'CAE', 3, 3, 3, 20);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (73, 'Energia', 3, 1, 1, 20);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (209, 'REN', 3, 215, 214, 207);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (176, 'Transporte de Valores', 3, 2, 2, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (102, 'Ruído', 3, 5, 5, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (77, 'Áreas Localização Empresarial', 3, 1, 0, 20);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (95, 'Código do Trabalho', 3, 28, 28, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (165, 'Geral', 3, 10, 9, 30);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (161, 'Equipamentos Eléctricos e Electrónicos', 3, 7, 7, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (205, 'Efluentes', 3, 7, 3, 32);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (48, 'Canídeos', 3, 1, 0, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (55, 'Desporto', 3, 1, 0, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (153, 'Óleos Novos e Usados', 3, 3, 3, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (156, 'Depósitos Minerais', 3, 1, 1, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (177, 'Recintos Desportivos', 3, 2, 1, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (131, 'Especificações Combustíveis', 3, 3, 3, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (41, 'Inspecção Geral MAI', 3, 1, 1, 10);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (98, 'Técnicos SHT', 3, 7, 5, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (50, 'Segurança Portuária', 3, 2, 2, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (60, 'Gravações Videovigilância', 3, 1, 1, 18);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (59, 'Rodoviária', 3, 1, 1, 17);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (63, 'Comunicações Electrónicas', 3, 1, 1, 18);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (69, 'Movimentação Manual Cargas', 3, 1, 1, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (89, 'Segurança de Barragens', 3, 3, 2, 23);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (4, 'Protecção Civil', 1, 59, 51, null);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (61, 'Forças de Segurança', 3, 4, 4, 17);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (80, 'Sinalização', 3, 5, 5, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (93, 'Trabalho Temporário', 3, 1, 1, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (62, 'Videovigilância', 3, 4, 4, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (103, 'Vibrações', 3, 1, 1, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (90, 'Coordenação Operacional', 3, 1, 0, 24);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (99, 'Notificação Serviços SHT', 3, 2, 2, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (113, 'Administrativos', 3, 0, 0, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (65, 'Código Processo Penal', 3, 2, 2, 19);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (40, 'Secretaria-Geral MAI', 3, 2, 2, 10);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (118, 'PCBs', 3, 2, 2, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (224, 'Fauna e Flora', 2, 8, 8, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (47, 'Segurança Privada', 3, 1, 0, 12);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (97, 'Serviços Externos', 3, 2, 2, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (116, 'Biocidas', 3, 16, 16, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (107, 'Laboratórios', 3, 2, 2, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (88, 'Comissão Nacional', 3, 2, 0, 24);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (96, 'Relatório Anual SHT', 3, 3, 2, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (58, 'Requisitos Centrais Recepção', 3, 1, 0, 16);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (57, 'Ligação a Centrais', 3, 2, 1, 16);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (46, 'Identificação Eletrónica', 3, 1, 1, 12);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (19, 'Códigos', 2, 4, 4, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (74, 'Gás Natural', 3, 33, 30, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (44, 'Licenciamento', 3, 1, 1, 12);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (111, 'Restauração e Bebidas', 3, 1, 1, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (56, 'Taxas Instalação', 3, 1, 1, 16);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (6, 'Ar', 2, 84, 73, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (45, 'Vigilância Sanitária', 3, 1, 1, 12);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (14, 'Estabelecimentos e Actividades', 2, 40, 39, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (91, 'Lei da Segurança Interna', 3, 6, 6, 9);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (108, 'Certificação Energética', 3, 24, 24, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (9, 'Geral', 2, 9, 9, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (31, 'Legislação de base', 2, 28, 22, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (32, 'Água', 2, 192, 178, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (76, 'Armazenamento Combustiveis', 3, 9, 9, 20);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (94, 'Ficha de Aptidão', 3, 2, 2, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (223, 'Brinquedos', 3, 3, 2, 22);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (64, 'Base Dados Pessoais', 3, 2, 2, 18);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (75, 'Postos Abast. Combustíveis', 3, 11, 11, 20);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (87, 'SIOPS', 3, 2, 1, 24);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (109, 'Maritímas e Portuárias', 3, 27, 27, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (214, 'Planos de Ordenamento', 3, 10, 7, 207);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (51, 'Aviação Civil', 3, 5, 5, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (114, 'Serviços', 3, 0, 0, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (21, 'Substâncias Perigosas', 2, 250, 222, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (225, 'Infra-estruturas críticas', 3, 1, 1, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (221, 'Segurança Alimentar', 2, 2, 2, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (222, 'Geral', 3, 2, 2, 221);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (215, 'Açores e Madeira', 3, 0, 0, 24);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (43, 'Formação', 3, 6, 5, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (227, 'Protecção Sísmica', 2, 1, 1, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (85, 'Comissão Distrital', 3, 1, 0, 24);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (23, 'Municipal', 2, 21, 16, 4);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (26, 'Geral', 2, 32, 30, 4);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (52, 'Bares, Discotecas e Boîtes', 3, 3, 3, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (68, 'Equipamentos Sob Pressão', 3, 15, 13, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (66, 'Exercício Actividade', 3, 11, 11, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (119, 'Aerossóis', 3, 5, 5, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (70, 'Segurança Contra Incêndios', 3, 26, 26, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (182, 'Sinalização', 3, 3, 3, 179);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (181, 'Incêndios Florestais', 3, 22, 18, 179);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (183, 'Incêndios Florestais', 3, 15, 12, 23);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (179, 'Segurança Contra Incêndios', 2, 53, 49, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (188, 'Marítimas e Portuárias', 3, 40, 38, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (186, 'Aviação Civil', 3, 2, 2, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (28, 'Resíduos', 2, 74, 71, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (185, 'Segurança Portuária', 3, 1, 1, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (191, 'Administração Pública', 3, 4, 4, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (196, 'Bebidas Alcoólicas', 3, 0, 1, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (35, 'Geral', 3, 4, 3, 7);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (86, 'Comissão Municipal', 3, 1, 0, 24);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (83, 'Parques aquáticos', 3, 7, 7, 22);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (7, 'Armas e Munições', 2, 4, 3, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (194, 'Campos de Férias', 3, 2, 3, 22);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (13, 'Transporte de Valores', 2, 2, 2, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (37, 'Ilícitos', 3, 3, 3, 9);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (29, 'Estudos Impacte Ambiental', 2, 15, 13, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (34, 'Poluentes Gasosos', 3, 11, 11, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (24, 'Nacional', 2, 16, 10, 4);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (78, 'Pecuária', 3, 8, 4, 20);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (12, 'Canídeos', 2, 4, 3, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (18, 'Protecção de Dados', 2, 4, 4, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (180, 'Edifícios (SCIE) ', 3, 28, 27, 179);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (39, 'Uniformes', 3, 1, 1, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (187, 'Bares, Discotecas e Boîtes', 3, 3, 2, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (199, 'Bares, Discotecas e Boîtes', 3, 2, 2, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (16, 'Alarmes', 2, 3, 2, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (15, 'Desporto', 2, 10, 7, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (33, 'Máquinas e Equipamentos', 3, 53, 51, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (42, 'GNR', 3, 5, 5, 10);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (11, 'Segurança Privada', 2, 29, 26, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (38, 'PSP', 3, 6, 6, 10);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (189, 'Restauração e Bebidas', 3, 8, 5, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (193, 'Serviços', 3, 5, 5, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (10, 'Entidades Públicas', 2, 11, 11, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (17, 'Videovigilância', 2, 5, 5, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (30, 'Licença Ambiental', 2, 10, 9, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (22, 'Segurança de Pessoas', 2, 20, 20, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (200, 'Radioactivos', 3, 4, 4, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (201, 'Estabelecimentos que recebem público', 3, 6, 6, 22);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (217, 'Instalações desportivas', 3, 2, 1, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (110, 'Comerciais', 3, 0, 0, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (203, 'Empreendimentos turísticos', 3, 12, 11, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (27, 'Ruído', 2, 12, 11, 2);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (100, 'Silicose', 3, 3, 3, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (115, 'Mergulho', 3, 3, 3, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (216, 'Instalações desportivas', 3, 3, 3, 22);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (81, 'EPI', 3, 8, 7, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (54, 'Assistentes desportivos', 3, 2, 0, 15);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (202, 'Edifícios habitacionais', 3, 1, 0, 22);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (53, 'Recintos Desportivos', 3, 10, 7, 15);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (150, 'Resíduos Industriais', 3, 3, 3, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (137, 'Transferência Poluentes', 3, 5, 5, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (128, 'SEVESO', 3, 9, 9, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (122, 'Chumbo / Cádmio / Mercúrio', 3, 1, 0, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (145, 'Sistemas Municipais', 3, 9, 9, 32);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (121, 'Cancerígenos e Mutagénicos', 3, 4, 2, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (139, 'Especificações Fuelóleos', 3, 1, 1, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (132, 'Camada Ozono', 3, 6, 6, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (92, 'Geral - ACT', 3, 5, 5, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (130, 'Gases Efeito Estufa', 3, 19, 14, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (160, 'Navios', 3, 6, 6, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (184, 'Transporte de Valores', 3, 2, 2, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (3, 'Security', 1, 109, 102, null);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (170, 'Geral', 3, 19, 15, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (129, 'Segurança em Obra', 3, 5, 5, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (163, 'Geral', 3, 28, 24, 32);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (174, 'Geral', 3, 27, 23, 20);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (143, 'Normas de Qualidade', 3, 11, 11, 32);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (125, 'Explosivos', 3, 22, 21, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (8, 'Jornalistas', 2, 1, 1, 3);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (133, 'Poluição Marinha', 3, 1, 1, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (204, 'Fitofarmacêuticos', 3, 42, 42, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (135, 'Ozono no Ar Ambiente', 3, 1, 1, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (36, 'Estatuto Jornalista', 3, 1, 1, 8);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (192, 'Administrativos', 3, 2, 2, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (140, 'Acesso à Informação', 3, 2, 2, 31);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (171, 'Geral', 3, 11, 6, 24);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (173, 'Geral', 3, 4, 2, 23);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (159, 'Pneus Usados', 3, 1, 1, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (151, 'Transferência de Resíduos', 3, 5, 5, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (127, 'Transporte', 3, 30, 20, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (142, 'Poluição', 3, 18, 18, 32);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (20, 'Licenciamento Industrial', 2, 53, 45, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (2, 'Ambiente', 1, 668, 634, null);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (141, 'Recurso e Domínio Hídrico', 3, 99, 96, 32);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (105, 'Estabelecimentos Industriais', 3, 2, 2, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (1, 'Safety', 1, 768, 705, null);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (195, 'Parques Infantis', 3, 3, 3, 22);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (5, 'SHT', 2, 301, 284, 1);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (197, 'Base Dados Pessoais', 3, 0, 0, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (124, 'Atmosferas Explosivas', 3, 3, 3, 5);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (198, 'Transporte Valores', 3, 2, 2, 11);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (190, 'Comerciais', 3, 15, 10, 178);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (169, 'Geral', 3, 53, 39, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (155, 'Transporte de Resíduos', 3, 3, 3, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (154, 'Aterros', 3, 6, 5, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (136, 'Poluentes Atmosféricos COV', 3, 3, 2, 6);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (158, 'Embalagens', 3, 8, 8, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (120, 'Amianto', 3, 8, 8, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (147, 'Obras e Demolições', 3, 3, 3, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (175, 'Geral', 3, 3, 2, 15);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (112, 'Administração Pública', 3, 0, 0, 14);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (126, 'Combustíveis', 3, 43, 40, 21);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (157, 'Pedreiras', 3, 3, 3, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (144, 'Águas Residuais', 3, 15, 13, 32);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (148, 'Veículos Fim de Vida', 3, 3, 3, 28);
INSERT INTO public.legaldocumentcategory (id, name, depth, allassociateddocumentscounter, activeassociateddocumentscounter, parentcategory_id) VALUES (101, 'Acidentes Trabalho', 3, 24, 19, 5);