INSERT INTO public.country (iso, name) VALUES ('AD', 'Andorra');
INSERT INTO public.country (iso, name) VALUES ('AE', 'Emiratos Árabes Unidos');
INSERT INTO public.country (iso, name) VALUES ('AF', 'Afeganistão');
INSERT INTO public.country (iso, name) VALUES ('AG', 'Antigua e Barbuda');
INSERT INTO public.country (iso, name) VALUES ('AI', 'Anguilla');
INSERT INTO public.country (iso, name) VALUES ('AL', 'Albânia');
INSERT INTO public.country (iso, name) VALUES ('AM', 'Arménia');
INSERT INTO public.country (iso, name) VALUES ('AN', 'Antilhas Holandesas');
INSERT INTO public.country (iso, name) VALUES ('AO', 'Angola');
INSERT INTO public.country (iso, name) VALUES ('AQ', 'Antárctida');
INSERT INTO public.country (iso, name) VALUES ('AR', 'Argentina');
INSERT INTO public.country (iso, name) VALUES ('AS', 'Samoa Americana');
INSERT INTO public.country (iso, name) VALUES ('AT', 'Áustria');
INSERT INTO public.country (iso, name) VALUES ('AU', 'Austrália');
INSERT INTO public.country (iso, name) VALUES ('AW', 'Aruba');
INSERT INTO public.country (iso, name) VALUES ('AX', 'Åland, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('AZ', 'Azerbeijão');
INSERT INTO public.country (iso, name) VALUES ('BA', 'Bósnia-Herzegovina');
INSERT INTO public.country (iso, name) VALUES ('BB', 'Barbados');
INSERT INTO public.country (iso, name) VALUES ('BD', 'Bangladesh');
INSERT INTO public.country (iso, name) VALUES ('BE', 'Bélgica');
INSERT INTO public.country (iso, name) VALUES ('BF', 'Burkina Faso');
INSERT INTO public.country (iso, name) VALUES ('BG', 'Bulgária');
INSERT INTO public.country (iso, name) VALUES ('BH', 'Bahrain');
INSERT INTO public.country (iso, name) VALUES ('BI', 'Burundi');
INSERT INTO public.country (iso, name) VALUES ('BJ', 'Benin');
INSERT INTO public.country (iso, name) VALUES ('BM', 'Bermuda');
INSERT INTO public.country (iso, name) VALUES ('BN', 'Brunei');
INSERT INTO public.country (iso, name) VALUES ('BO', 'Bolívia');
INSERT INTO public.country (iso, name) VALUES ('BR', 'Brasil');
INSERT INTO public.country (iso, name) VALUES ('BS', 'Bahamas');
INSERT INTO public.country (iso, name) VALUES ('BT', 'Butão');
INSERT INTO public.country (iso, name) VALUES ('BV', 'Bouvet, Ilha');
INSERT INTO public.country (iso, name) VALUES ('BW', 'Botswana');
INSERT INTO public.country (iso, name) VALUES ('BY', 'Bielo-Rússia');
INSERT INTO public.country (iso, name) VALUES ('BZ', 'Belize');
INSERT INTO public.country (iso, name) VALUES ('CA', 'Canadá');
INSERT INTO public.country (iso, name) VALUES ('CC', 'Cocos, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('CD', 'Congo, República Democrática do (antigo Zaire)');
INSERT INTO public.country (iso, name) VALUES ('CF', 'Centro-africana, República');
INSERT INTO public.country (iso, name) VALUES ('CG', 'Congo, República do');
INSERT INTO public.country (iso, name) VALUES ('CH', 'Suíça');
INSERT INTO public.country (iso, name) VALUES ('CI', 'Costa do Marfim');
INSERT INTO public.country (iso, name) VALUES ('CK', 'Cook, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('CL', 'Chile');
INSERT INTO public.country (iso, name) VALUES ('CM', 'Camarões');
INSERT INTO public.country (iso, name) VALUES ('CN', 'China');
INSERT INTO public.country (iso, name) VALUES ('CO', 'Colômbia');
INSERT INTO public.country (iso, name) VALUES ('CR', 'Costa Rica');
INSERT INTO public.country (iso, name) VALUES ('CU', 'Cuba');
INSERT INTO public.country (iso, name) VALUES ('CV', 'Cabo Verde');
INSERT INTO public.country (iso, name) VALUES ('CX', 'Christmas, Ilha');
INSERT INTO public.country (iso, name) VALUES ('CY', 'Chipre');
INSERT INTO public.country (iso, name) VALUES ('CZ', 'Checa, República');
INSERT INTO public.country (iso, name) VALUES ('DE', 'Alemanha');
INSERT INTO public.country (iso, name) VALUES ('DJ', 'Djibouti');
INSERT INTO public.country (iso, name) VALUES ('DK', 'Dinamarca');
INSERT INTO public.country (iso, name) VALUES ('DM', 'Dominica');
INSERT INTO public.country (iso, name) VALUES ('DO', 'Dominicana, República');
INSERT INTO public.country (iso, name) VALUES ('DZ', 'Argélia');
INSERT INTO public.country (iso, name) VALUES ('EC', 'Equador');
INSERT INTO public.country (iso, name) VALUES ('EE', 'Estónia');
INSERT INTO public.country (iso, name) VALUES ('EG', 'Egipto');
INSERT INTO public.country (iso, name) VALUES ('EH', 'Saara Ocidental');
INSERT INTO public.country (iso, name) VALUES ('ER', 'Eritreia');
INSERT INTO public.country (iso, name) VALUES ('ES', 'Espanha');
INSERT INTO public.country (iso, name) VALUES ('ET', 'Etiópia');
INSERT INTO public.country (iso, name) VALUES ('FI', 'Finlândia');
INSERT INTO public.country (iso, name) VALUES ('FJ', 'Fiji');
INSERT INTO public.country (iso, name) VALUES ('FK', 'Malvinas, Ilhas (Falkland)');
INSERT INTO public.country (iso, name) VALUES ('FM', 'Micronésia, Estados Federados da');
INSERT INTO public.country (iso, name) VALUES ('FO', 'Faroe, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('FR', 'França');
INSERT INTO public.country (iso, name) VALUES ('GA', 'Gabão');
INSERT INTO public.country (iso, name) VALUES ('GB', 'Reino Unido da Grã-Bretanha e Irlanda do Norte');
INSERT INTO public.country (iso, name) VALUES ('GD', 'Grenada');
INSERT INTO public.country (iso, name) VALUES ('GE', 'Geórgia');
INSERT INTO public.country (iso, name) VALUES ('GF', 'Guiana Francesa');
INSERT INTO public.country (iso, name) VALUES ('GG', 'Guernsey');
INSERT INTO public.country (iso, name) VALUES ('GH', 'Gana');
INSERT INTO public.country (iso, name) VALUES ('GI', 'Gibraltar');
INSERT INTO public.country (iso, name) VALUES ('GL', 'Gronelândia');
INSERT INTO public.country (iso, name) VALUES ('GM', 'Gâmbia');
INSERT INTO public.country (iso, name) VALUES ('GN', 'Guiné-Conacri');
INSERT INTO public.country (iso, name) VALUES ('GP', 'Guadeloupe');
INSERT INTO public.country (iso, name) VALUES ('GQ', 'Guiné Equatorial');
INSERT INTO public.country (iso, name) VALUES ('GR', 'Grécia');
INSERT INTO public.country (iso, name) VALUES ('GS', 'Geórgia do Sul e Sandwich do Sul, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('GT', 'Guatemala');
INSERT INTO public.country (iso, name) VALUES ('GU', 'Guam');
INSERT INTO public.country (iso, name) VALUES ('GW', 'Guiné-Bissau');
INSERT INTO public.country (iso, name) VALUES ('GY', 'Guiana');
INSERT INTO public.country (iso, name) VALUES ('HK', 'Hong Kong');
INSERT INTO public.country (iso, name) VALUES ('HM', 'Heard e Ilhas McDonald, Ilha');
INSERT INTO public.country (iso, name) VALUES ('HN', 'Honduras');
INSERT INTO public.country (iso, name) VALUES ('HR', 'Croácia');
INSERT INTO public.country (iso, name) VALUES ('HT', 'Haiti');
INSERT INTO public.country (iso, name) VALUES ('HU', 'Hungria');
INSERT INTO public.country (iso, name) VALUES ('ID', 'Indonésia');
INSERT INTO public.country (iso, name) VALUES ('IE', 'Irlanda');
INSERT INTO public.country (iso, name) VALUES ('IL', 'Israel');
INSERT INTO public.country (iso, name) VALUES ('IM', 'Man, Ilha de');
INSERT INTO public.country (iso, name) VALUES ('IN', 'Índia');
INSERT INTO public.country (iso, name) VALUES ('IO', 'Território Britânico do Oceano Índico');
INSERT INTO public.country (iso, name) VALUES ('IQ', 'Iraque');
INSERT INTO public.country (iso, name) VALUES ('IR', 'Irão');
INSERT INTO public.country (iso, name) VALUES ('IS', 'Islândia');
INSERT INTO public.country (iso, name) VALUES ('IT', 'Itália');
INSERT INTO public.country (iso, name) VALUES ('JE', 'Jersey');
INSERT INTO public.country (iso, name) VALUES ('JM', 'Jamaica');
INSERT INTO public.country (iso, name) VALUES ('JO', 'Jordânia');
INSERT INTO public.country (iso, name) VALUES ('JP', 'Japão');
INSERT INTO public.country (iso, name) VALUES ('KE', 'Quénia');
INSERT INTO public.country (iso, name) VALUES ('KG', 'Quirguistão');
INSERT INTO public.country (iso, name) VALUES ('KH', 'Cambodja');
INSERT INTO public.country (iso, name) VALUES ('KI', 'Kiribati');
INSERT INTO public.country (iso, name) VALUES ('KM', 'Comores');
INSERT INTO public.country (iso, name) VALUES ('KN', 'São Cristóvão e Névis (Saint Kitts e Nevis)');
INSERT INTO public.country (iso, name) VALUES ('KP', 'Coreia, República Democrática da (Coreia do Norte)');
INSERT INTO public.country (iso, name) VALUES ('KR', 'Coreia do Sul');
INSERT INTO public.country (iso, name) VALUES ('KW', 'Kuwait');
INSERT INTO public.country (iso, name) VALUES ('KY', 'Cayman, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('KZ', 'Cazaquistão');
INSERT INTO public.country (iso, name) VALUES ('LA', 'Laos');
INSERT INTO public.country (iso, name) VALUES ('LB', 'Líbano');
INSERT INTO public.country (iso, name) VALUES ('LC', 'Santa Lúcia');
INSERT INTO public.country (iso, name) VALUES ('LI', 'Liechtenstein');
INSERT INTO public.country (iso, name) VALUES ('LK', 'Sri Lanka');
INSERT INTO public.country (iso, name) VALUES ('LR', 'Libéria');
INSERT INTO public.country (iso, name) VALUES ('LS', 'Lesoto');
INSERT INTO public.country (iso, name) VALUES ('LT', 'Lituânia');
INSERT INTO public.country (iso, name) VALUES ('LU', 'Luxemburgo');
INSERT INTO public.country (iso, name) VALUES ('LV', 'Letónia');
INSERT INTO public.country (iso, name) VALUES ('LY', 'Líbia');
INSERT INTO public.country (iso, name) VALUES ('MA', 'Marrocos');
INSERT INTO public.country (iso, name) VALUES ('MC', 'Mónaco');
INSERT INTO public.country (iso, name) VALUES ('MD', 'Moldávia');
INSERT INTO public.country (iso, name) VALUES ('ME', 'Montenegro');
INSERT INTO public.country (iso, name) VALUES ('MG', 'Madagáscar');
INSERT INTO public.country (iso, name) VALUES ('MH', 'Marshall, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('MK', 'Macedónia, República da');
INSERT INTO public.country (iso, name) VALUES ('ML', 'Mali');
INSERT INTO public.country (iso, name) VALUES ('MM', 'Myanmar (antiga Birmânia)');
INSERT INTO public.country (iso, name) VALUES ('MN', 'Mongólia');
INSERT INTO public.country (iso, name) VALUES ('MO', 'Macau');
INSERT INTO public.country (iso, name) VALUES ('MP', 'Marianas Setentrionais');
INSERT INTO public.country (iso, name) VALUES ('MQ', 'Martinica');
INSERT INTO public.country (iso, name) VALUES ('MR', 'Mauritânia');
INSERT INTO public.country (iso, name) VALUES ('MS', 'Montserrat');
INSERT INTO public.country (iso, name) VALUES ('MT', 'Malta');
INSERT INTO public.country (iso, name) VALUES ('MU', 'Maurícia');
INSERT INTO public.country (iso, name) VALUES ('MV', 'Maldivas');
INSERT INTO public.country (iso, name) VALUES ('MW', 'Malawi');
INSERT INTO public.country (iso, name) VALUES ('MX', 'México');
INSERT INTO public.country (iso, name) VALUES ('MY', 'Malásia');
INSERT INTO public.country (iso, name) VALUES ('MZ', 'Moçambique');
INSERT INTO public.country (iso, name) VALUES ('NA', 'Namíbia');
INSERT INTO public.country (iso, name) VALUES ('NC', 'Nova Caledónia');
INSERT INTO public.country (iso, name) VALUES ('NE', 'Níger');
INSERT INTO public.country (iso, name) VALUES ('NF', 'Norfolk, Ilha');
INSERT INTO public.country (iso, name) VALUES ('NG', 'Nigéria');
INSERT INTO public.country (iso, name) VALUES ('NI', 'Nicarágua');
INSERT INTO public.country (iso, name) VALUES ('NL', 'Países Baixos (Holanda)');
INSERT INTO public.country (iso, name) VALUES ('NO', 'Noruega');
INSERT INTO public.country (iso, name) VALUES ('NP', 'Nepal');
INSERT INTO public.country (iso, name) VALUES ('NR', 'Nauru');
INSERT INTO public.country (iso, name) VALUES ('NU', 'Niue');
INSERT INTO public.country (iso, name) VALUES ('NZ', 'Nova Zelândia (Aotearoa)');
INSERT INTO public.country (iso, name) VALUES ('OM', 'Oman');
INSERT INTO public.country (iso, name) VALUES ('PA', 'Panamá');
INSERT INTO public.country (iso, name) VALUES ('PE', 'Peru');
INSERT INTO public.country (iso, name) VALUES ('PF', 'Polinésia Francesa');
INSERT INTO public.country (iso, name) VALUES ('PG', 'Papua-Nova Guiné');
INSERT INTO public.country (iso, name) VALUES ('PH', 'Filipinas');
INSERT INTO public.country (iso, name) VALUES ('PK', 'Paquistão');
INSERT INTO public.country (iso, name) VALUES ('PL', 'Polónia');
INSERT INTO public.country (iso, name) VALUES ('PM', 'Saint Pierre et Miquelon');
INSERT INTO public.country (iso, name) VALUES ('PN', 'Pitcairn');
INSERT INTO public.country (iso, name) VALUES ('PR', 'Porto Rico');
INSERT INTO public.country (iso, name) VALUES ('PS', 'Palestina');
INSERT INTO public.country (iso, name) VALUES ('PT', 'Portugal');
INSERT INTO public.country (iso, name) VALUES ('PW', 'Palau');
INSERT INTO public.country (iso, name) VALUES ('PY', 'Paraguai');
INSERT INTO public.country (iso, name) VALUES ('QA', 'Qatar');
INSERT INTO public.country (iso, name) VALUES ('RE', 'Reunião');
INSERT INTO public.country (iso, name) VALUES ('RO', 'Roménia');
INSERT INTO public.country (iso, name) VALUES ('RS', 'Sérvia');
INSERT INTO public.country (iso, name) VALUES ('RU', 'Rússia');
INSERT INTO public.country (iso, name) VALUES ('RW', 'Ruanda');
INSERT INTO public.country (iso, name) VALUES ('SA', 'Arábia Saudita');
INSERT INTO public.country (iso, name) VALUES ('SB', 'Salomão, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('SC', 'Seychelles');
INSERT INTO public.country (iso, name) VALUES ('SD', 'Sudão');
INSERT INTO public.country (iso, name) VALUES ('SE', 'Suécia');
INSERT INTO public.country (iso, name) VALUES ('SG', 'Singapura');
INSERT INTO public.country (iso, name) VALUES ('SH', 'Santa Helena');
INSERT INTO public.country (iso, name) VALUES ('SI', 'Eslovénia');
INSERT INTO public.country (iso, name) VALUES ('SJ', 'Svalbard e Jan Mayen');
INSERT INTO public.country (iso, name) VALUES ('SK', 'Eslováquia');
INSERT INTO public.country (iso, name) VALUES ('SL', 'Serra Leoa');
INSERT INTO public.country (iso, name) VALUES ('SM', 'San Marino');
INSERT INTO public.country (iso, name) VALUES ('SN', 'Senegal');
INSERT INTO public.country (iso, name) VALUES ('SO', 'Somália');
INSERT INTO public.country (iso, name) VALUES ('SR', 'Suriname');
INSERT INTO public.country (iso, name) VALUES ('ST', 'São Tomé e Príncipe');
INSERT INTO public.country (iso, name) VALUES ('SV', 'El Salvador');
INSERT INTO public.country (iso, name) VALUES ('SY', 'Síria');
INSERT INTO public.country (iso, name) VALUES ('SZ', 'Suazilândia');
INSERT INTO public.country (iso, name) VALUES ('TC', 'Turks e Caicos');
INSERT INTO public.country (iso, name) VALUES ('TD', 'Chade');
INSERT INTO public.country (iso, name) VALUES ('TF', 'Terras Austrais e Antárticas Francesas (TAAF)');
INSERT INTO public.country (iso, name) VALUES ('TG', 'Togo');
INSERT INTO public.country (iso, name) VALUES ('TH', 'Tailândia');
INSERT INTO public.country (iso, name) VALUES ('TJ', 'Tajiquistão');
INSERT INTO public.country (iso, name) VALUES ('TK', 'Toquelau');
INSERT INTO public.country (iso, name) VALUES ('TL', 'Timor-Leste');
INSERT INTO public.country (iso, name) VALUES ('TM', 'Turquemenistão');
INSERT INTO public.country (iso, name) VALUES ('TN', 'Tunísia');
INSERT INTO public.country (iso, name) VALUES ('TO', 'Tonga');
INSERT INTO public.country (iso, name) VALUES ('TR', 'Turquia');
INSERT INTO public.country (iso, name) VALUES ('TT', 'Trindade e Tobago');
INSERT INTO public.country (iso, name) VALUES ('TV', 'Tuvalu');
INSERT INTO public.country (iso, name) VALUES ('TW', 'Taiwan');
INSERT INTO public.country (iso, name) VALUES ('TZ', 'Tanzânia');
INSERT INTO public.country (iso, name) VALUES ('UA', 'Ucrânia');
INSERT INTO public.country (iso, name) VALUES ('UG', 'Uganda');
INSERT INTO public.country (iso, name) VALUES ('UM', 'Menores Distantes dos Estados Unidos, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('US', 'Estados Unidos da América');
INSERT INTO public.country (iso, name) VALUES ('UY', 'Uruguai');
INSERT INTO public.country (iso, name) VALUES ('UZ', 'Usbequistão');
INSERT INTO public.country (iso, name) VALUES ('VA', 'Vaticano');
INSERT INTO public.country (iso, name) VALUES ('VC', 'São Vicente e Granadinas');
INSERT INTO public.country (iso, name) VALUES ('VE', 'Venezuela');
INSERT INTO public.country (iso, name) VALUES ('VG', 'Virgens Britânicas, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('VI', 'Virgens Americanas, Ilhas');
INSERT INTO public.country (iso, name) VALUES ('VN', 'Vietname');
INSERT INTO public.country (iso, name) VALUES ('VU', 'Vanuatu');
INSERT INTO public.country (iso, name) VALUES ('WF', 'Wallis e Futuna');
INSERT INTO public.country (iso, name) VALUES ('WS', 'Samoa (Samoa Ocidental)');
INSERT INTO public.country (iso, name) VALUES ('YE', 'Iémen');
INSERT INTO public.country (iso, name) VALUES ('YT', 'Mayotte');
INSERT INTO public.country (iso, name) VALUES ('ZA', 'África do Sul');
INSERT INTO public.country (iso, name) VALUES ('ZM', 'Zâmbia');
INSERT INTO public.country (iso, name) VALUES ('ZW', 'Zimbabwe');